In [1]:
import pandas as pd

df=pd.read_csv('train.csv')


In [2]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [3]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [4]:
##drop the null values

df=df.dropna()   ##it removes the null values

In [5]:
##taking the dependent feature and dependent features

X=df.drop('label',axis=1)



In [8]:
##get the dependent features
y=df['label']

In [9]:
X

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [10]:
y

0        1
1        0
2        1
3        1
4        1
        ..
20795    0
20796    0
20797    0
20798    1
20799    1
Name: label, Length: 18285, dtype: int64

In [14]:
import tensorflow as tf


In [15]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense


In [16]:
##vocubalary size
voc_size=10000


In [17]:
##one hot encoding

message=X.copy()

message['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [18]:
message

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [20]:
message.reset_index(inplace=True)

In [21]:
import nltk
import re
from nltk.corpus import stopwords

In [22]:
nltk.download('stopwords')


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [23]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()


In [24]:
mesaages=message.head(20)

In [28]:
corpus = []
for i in range(0 , len(message)):
    review = re.sub('[^a-zA-Z]', '  ', message['title'][i])
    review = review.lower()
    review = review.split()
    
    review =[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [27]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [29]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr


[[1063, 6729, 2073, 6037, 4371, 5245, 9319, 7444, 7087, 3567],
 [1952, 1218, 79, 6309, 6190, 1684, 1799],
 [2807, 3486, 9610, 803],
 [9267, 1529, 659, 6731, 3176, 9536],
 [1844, 6190, 5818, 7313, 7426, 968, 6190, 7445, 2564, 6220],
 [8287,
  9282,
  8724,
  3245,
  5327,
  1978,
  1365,
  4851,
  1960,
  120,
  5598,
  7287,
  9626,
  6655,
  1799],
 [3348, 9524, 161, 5811, 5337, 9043, 1623, 6875, 7648, 6715, 4793],
 [7595, 3202, 1019, 3904, 8095, 501, 1978, 8096, 7648, 6715, 4793],
 [3788, 7841, 3658, 3590, 3298, 4562, 447, 6065, 1978, 1171],
 [2372, 9898, 5586, 7424, 8836, 1600, 6274, 8736],
 [7082, 3588, 3435, 6233, 1509, 6408, 7393, 4231, 9501, 3191, 9350],
 [6731, 3, 4371, 4562, 1978, 8095],
 [5598, 316, 510, 6268, 6292, 3936, 5185, 1902, 6573],
 [3672, 495, 2000, 9283, 9600, 9993, 6828, 7648, 6715, 4793],
 [8859, 6503, 8550, 6705, 2202, 7648, 6715, 4793],
 [4853, 6009, 1855, 4375, 9225, 762, 3942, 3028, 5890, 8325],
 [7047, 6279, 1218],
 [2680, 6459, 4297, 2612, 1978, 5736, 1159,

In [31]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [33]:
##embedding representation

sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)


[[   0    0    0 ... 7444 7087 3567]
 [   0    0    0 ... 6190 1684 1799]
 [   0    0    0 ... 3486 9610  803]
 ...
 [   0    0    0 ... 7648 6715 4793]
 [   0    0    0 ... 1900 5478   61]
 [   0    0    0 ... 6597 7228 2613]]


In [34]:
embedded_docs[1]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0, 1952, 1218,   79, 6309, 6190, 1684, 1799])

In [38]:
#creatung the model

embedding_vector_features=40 ##each and every word in previous array is converted into a vector
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid')) ##whenever my output is 1 or 0 use sigmoid activation
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 20, 40)            400000    
                                                                 
 lstm_2 (LSTM)               (None, 100)               56400     
                                                                 
 dense_2 (Dense)             (None, 1)                 101       
                                                                 
Total params: 456,501
Trainable params: 456,501
Non-trainable params: 0
_________________________________________________________________
None


In [39]:
import numpy as np
X_final=np.array(embedded_docs) ##just converting the lists into array
y_final=np.array(y)

In [40]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [41]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_final,y_final,test_size=0.33,random_state=42)

In [44]:
##nodel_training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 6s 22ms/step - loss: 0.3450 - accuracy: 0.8527 - val_loss: 0.1988 - val_accuracy: 0.9157
Epoch 2/10
192/192 [==============================] - 4s 20ms/step - loss: 0.1294 - accuracy: 0.9499 - val_loss: 0.1937 - val_accuracy: 0.9239
Epoch 3/10
192/192 [==============================] - 4s 20ms/step - loss: 0.0804 - accuracy: 0.9712 - val_loss: 0.2194 - val_accuracy: 0.9138
Epoch 4/10
192/192 [==============================] - 4s 20ms/step - loss: 0.0469 - accuracy: 0.9849 - val_loss: 0.2999 - val_accuracy: 0.9155
Epoch 5/10
192/192 [==============================] - 4s 20ms/step - loss: 0.0242 - accuracy: 0.9915 - val_loss: 0.3653 - val_accuracy: 0.9062
Epoch 6/10
192/192 [==============================] - 4s 20ms/step - loss: 0.0159 - accuracy: 0.9958 - val_loss: 0.4667 - val_accuracy: 0.9077
Epoch 7/10
192/192 [==============================] - 4s 20ms/step - loss: 0.0091 - accuracy: 0.9976 - val_loss: 0.4418 - val_accuracy: 0.9123

Performance metrics and accuracy

In [45]:
y_pred = model.predict(X_test)


189/189 [==============================] - 1s 4ms/step


In [46]:
y_pred=np.where(y_pred > 0.5,1,0)

In [47]:
from sklearn.metrics import confusion_matrix

In [49]:
confusion_matrix(y_test,y_pred)

array([[3081,  338],
       [ 185, 2431]], dtype=int64)

In [50]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9133388566694284

In [53]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      0.90      0.92      3419
           1       0.88      0.93      0.90      2616

    accuracy                           0.91      6035
   macro avg       0.91      0.92      0.91      6035
weighted avg       0.91      0.91      0.91      6035

